FROM python:3.10-slim

WORKDIR /app

COPY . .

RUN apt-get update && apt-get install -y stockfish

RUN pip install --no-cache-dir -r requirements.txt

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]